language: java
jdk:
  - openjdk17

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

before_deploy:
  - zip -r springbootidu *
  - mkdir -p deploy
  - mv springbootidu.zip deploy/springbootidu.zip


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springbootidu-build
    region: ap-northeast-2
    on:
      branch: main
    skip_cleanup: true
    acl: private
    local_dir: deploy

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springbootidu-build
    key: springbootidu.zip
    bundle_type: zip
    application: springbootidu
    deployment_group: springbootidu-group
    region: ap-northeast-2

before_install:
  - chmod +x gradlew

notifications:
  email:
    recipients:
      - kyuyoungk@naver.com