language: java
jdk:
  - openjdk17
branches:
  only:
    - master

before_install:
  - chmod +x gradlew
before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동 후 모든 파일을 before-deploy.zip 파일로 압축
  - cd .. && mkdir -p deploy # 상위 디렉토리로 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/springbootidu.zip # deploy로 zip파일 이동


#  - zip -r springbootidu *
#  - mkdir -p deploy
#  - mv springbootidu.zip deploy/springbootidu.zip

deploy:

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo setting 설정값
    secret_access_key: $AWS_SECRET_KEY # Travis repo setting 설정값

    bucket: springbootidu-build # s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private
    local_dir: deploy # before_deploy 에서 생성한 디렉토리

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY #Travis repo setting 설정값
    secret_access_key: $AWS_SECRET_KEY # Travis repo setting 설정값

    bucket: springbootidu-build # s3 버킷
    key: springbootidu.zip #빌드파일을 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: springbootidu # 웹 콘솔에서 등록한 CodeDeploy 앱
    deployment_group: springbootidu-group # 웹 콘솔에서 등록한 CodeDeploy 배포그룹

    region: ap-northeast-2
#Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"
#CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - kyuyoungk@naver.com