language: java
jdk:
  - openjdk17
branches:
  only:
    - master

before_install:
  - chmod +x gradlew
before_deploy:
  - zip -r springbootidu *
  - mkdir -p deploy
  - mv springbootidu.zip deploy/springbootidu.zip

deploy:

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo setting 설정값
    secret_access_key: $AWS_SECRET_KEY # Travis repo setting 설정값

    bucket: springbootidu-build # s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private
    local_dir: deploy # before_deploy 에서 생성한 디렉토리
    wait_until_deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY #Travis repo setting 설정값
    secret_access_key: $AWS_SECRET_KEY # Travis repo setting 설정값

    bucket: springbootidu-build # s3 버킷
    key: springbootidu.zip #빌드파일을 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: springbootidu # 웹 콘솔에서 등록한 CodeDeploy 앱
    deployment_group: springbootidu-group # 웹 콘솔에서 등록한 CodeDeploy 배포그룹

    region: ap-northeast-2
    wait-until-deployed: true
#Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"
#CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - kyuyoungk@naver.com