language: java
jdk:
  - openjdk17

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

before_deploy:
  - zip -r springbootidu *
  - mkdir -p deploy
  - mv springbootidu.zip deploy/springbootidu.zip


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springbootidu-build # s3 버킷
    region: ap-northeast-2
    on:
      branch: main
    skip_cleanup: true
    acl: private
    local_dir: deploy

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: springbootidu-build # s3 버킷
    key: springbootidu.zip #빌드파일을 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: springbootidu # 웹 콘솔에서 등록한 CodeDeploy 앱
    deployment_group: springbootidu-group # 웹 콘솔에서 등록한 CodeDeploy 배포그룹

    region: ap-northeast-2
    on:
      branch: main

before_install:
  - chmod +x gradlew

notifications:
  email:
    recipients:
      - kyuyoungk@naver.com